name: salsa-env

channels:
  - conda-forge

#NOTE: gcc compiler is needed to install some packages
dependencies:
    - python==3.11
    - pip
    - mpi4py
    - numpy
    - scipy
    - yt==4.2.0
    - pandas
    - pip:
        - trident==1.3.0
