name: salsa-env

channels:
  - conda-forge

#NOTE: gcc compiler is needed to install some packages
dependencies:
    - python==3.7
    - pip
    - mpi4py
    - matplotlib<=3.3.4
    - numpy
    - scipy
    - yt<=3.6.1
    - pandas
    - astropy==3.2.3
    - pip:
        - trident
        - spectacle
        - specutils==0.6.1
        - gwcs==0.11.0
